[tool.black]
line-length = 100
include = '(boto3|tests)/.*\.pyi?$'
target-version = [
    'py36',
    'py37',
    'py38',
]

[tool.isort]
multi_line_output = 3
include_trailing_comma= true
force_grid_wrap = 0
use_parentheses = true
line_length = 100
known_first_party = 'boto3'

[tool.coverage.run]
branch = true
include = [
    'boto3/*'
]
